### ISSUE TITLE
Handling edge cases

### ISSUE THREAD

**Issue by maayanorner** [tollefj/coreference-eval#1]
Hello,

First of all thanks for your contribution.
I have observed some issue. Assuming I have some document with corefs, but the model doesn't detect any, I get:
ZeroDivisionError: float division by zero

To reproduce:
```
# gold and pred are example inputs
gold = [[[50, 50], [27, 27], [29, 29]], [[0, 1], [7, 13]], [[1,2]]]
pred = [[[50, 50], [27, 27], [29, 29]], [[0, 1], [42, 42], [7, 13]], []]

get_metrics(pred, gold)
```
I believe additional details are not required as the error is pretty simple to detect, but for example:
tp += correct / float(len(c)) yields this error, it's a clear case of not handling this edge case, i.e., the implementation is not safe for a reasonable case (I guess).

The following code does work as expected, though:
```
gold = [[[50, 50], [27, 27], [29, 29]], [[0, 1], [7, 13]], [[1,2]]]
pred = [[[50, 50], [27, 27], [29, 29]], [[0, 1], [42, 42], [7, 13]], [[]]]

```
Thanks!

**Comment by tollefj** [comment]
How would you suggest to handle odd predictions like this from a model? Remove them entirely or consider them as a false prediction?

**Comment by maayanorner** [comment]
Good question, I am not sure... I think both solutions are very reasonable, assuming the paper doesn't specify how to handle it (which is probably the case, didn't read all of the papers). However, I would add a warning so it wouldn't happen silently. Another option is perhaps raising an exception for invalid input(?), something like ValueError. I guess it's your design decision, I do not know enough about the project to give good advice :)
Edit: I would lean towards considering them as a false prediction... Because the first can "give a prize" for bad predictions and some people may miss it and report incorrect results in papers.

**Comment by tollefj** [comment]
Yeah, I haven't encountered the issue before in coreference papers. Likely, most systems do not create these empty suggestions though. I'll browse around a bit and then update the repo.
